/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-21 05:12:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import java.io.*;
import service.*;
import domain.*;
import java.util.List;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;

public final class d_005f02_005fm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("service");
    _jspx_imports_packages.add("domain");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"assets/img/favicon.ico\">\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"./static/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<!-- CSS here -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Cinzel&family=Noto+Serif+KR:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#name\").bind(\"keyup\",function(){\r\n");
      out.write("\r\n");
      out.write("\t var re = /[~!@#$%^&*\\()\\=+_']/gi; \r\n");
      out.write("\r\n");
      out.write("\t var temp=$(\"#name\").val();\r\n");
      out.write("\r\n");
      out.write("\t if(re.test(temp)){ //특수문자가 포함되면 삭제하여 값으로 다시셋팅\r\n");
      out.write("\r\n");
      out.write("\t $(\"#name\").val(temp.replace(re,\"\")); } });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".error\").hide();//기본적으로 error클래스는 숨긴다\r\n");
      out.write("\t\t$(\"#submit\").click( function(event){//add가 클릭했을 때\r\n");
      out.write("\t\t\tvar name   = $(\"#name\").val();//name은 #name의 값\r\n");
      out.write("\t\t\tvar reg = /^[a-zA-Zㄱ-힣0-9]*$/;\r\n");
      out.write("\t\t\tvar reg2 = /^[a-zA-Zㄱ-힣]*$/;\t\t\t\r\n");
      out.write("\t\t\tvar nameLen    = name.length;\r\n");
      out.write("\t\t\tif(nameLen < 2){//글자수가 0이면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_01\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_01\").text(\"이름은 2글자 이상 써주세요\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if (!reg2.test(name)) {\r\n");
      out.write("\t\t\t\t$(\"#errMsg_01\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_01\").text(\"잘못된 이름\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else {//아니면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_01\").hide();//숨김\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar inname   = $(\"#inname\").val();//name은 #name의 값\r\n");
      out.write("\t\t\tvar innameLen    = inname.length;\r\n");
      out.write("\t\t\tif(innameLen < 1){//글자수가 0이면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_02\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_02\").text(\"비어있음\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if (!reg.test(inname)) {\r\n");
      out.write("\t\t\t\t$(\"#errMsg_02\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_02\").text(\"잘못된 이름\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t} else {//아니면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_02\").hide();//숨김\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar tel   = $(\"#tel\").val();//name은 #name의 값\r\n");
      out.write("\t\t\tvar telreg = /^\\d{2,3}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("\t\t\tvar telLen    = tel.length;\r\n");
      out.write("\t\t\tif(telLen < 1){//글자수가 0이면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_03\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_03\").text(\"비어있음\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if (!telreg.test(tel)) {\r\n");
      out.write("\t\t\t\t$(\"#errMsg_03\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_03\").text(\"잘못된 입력\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t} else {//아니면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_03\").hide();//숨김\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar addr   = $(\"#addr\").val();//name은 #name의 값\r\n");
      out.write("\t\t\tvar addrLen    = addr.length;\r\n");
      out.write("\t\t\tif(addrLen < 1){//글자수가 0이면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_04\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_04\").text(\"비어있음\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if (!reg.test(addr)) {\r\n");
      out.write("\t\t\t\t$(\"#errMsg_04\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_04\").text(\"잘못된 입력\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t} else {//아니면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_04\").hide();//숨김\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar date   = $(\"#date\").val();//name은 #name의 값\r\n");
      out.write("\t\t\tvar dateLen    = date.length;\r\n");
      out.write("\t\t\tif(dateLen < 1){//글자수가 0이면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_05\").show();\r\n");
      out.write("\t\t\t\t$(\"#errMsg_05\").text(\"비어있음\"); //출력\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t} else {//아니면\r\n");
      out.write("\t\t\t\t$(\"#errMsg_05\").hide();//숨김\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body BACKGROUND=\"./image/bg.png\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Preloader Start -->\r\n");
      out.write("\t<div id=\"preloader-active\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"preloader-inner position-relative\">\r\n");
      out.write("\t\t\t\t<div class=\"preloader-circle\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"preloader-img pere-text\">\r\n");
      out.write("\t\t\t\t\t<strong>Real Light</b>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Preloader Start -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	Calendar c = Calendar.getInstance();
	Calendar cal = Calendar.getInstance();
	cal.add(cal.DATE, +29);
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	String now = sdf.format(c.getTime());
	String after = sdf.format(cal.getTime());
	
		request.setCharacterEncoding("utf-8");//인코딩	
	String date = request.getParameter("date");
	String sRoom = request.getParameter("room");
	
	int room = 0;
	if (sRoom != null) {
		room = Integer.parseInt(sRoom);
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form method=post name=form action=\"./d_02_write.jsp\" style=\"font-family: 'Cinzel', serif;\">\r\n");
      out.write("\t\t\t<table cellspacing=1 border=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Name</td>\r\n");
      out.write("\t\t\t\t\t<td width=350><input type=\"text\" name=\"name\" id=\"name\" style=\"font-family: 'Noto Serif KR', serif; width:90px;\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\" id=\"errMsg_01\" style=\"font-size: 1em\" style=\"font-family: 'Noto Serif KR', serif;\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Date</td>\r\n");
      out.write("\t\t\t\t\t<td width=350>\r\n");
      out.write("\t\t\t\t\t\t");

							if (date != null) {
						
      out.write(" <input type=\"text\" value=");
      out.print(date);
      out.write(" name=\"date\" width:100px; readonly>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write(" <input type=\"date\" name=\"date\" id=\"date\" min=\"");
      out.print(now);
      out.write("\" max=\"");
      out.print(after);
      out.write("\" style=\"font-family: 'Noto Serif KR', serif; width:100px;\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\" id=\"errMsg_05\" style=\"font-size: 1em\" style=\"font-family: 'Noto Serif KR', serif;\"></span> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Room</td>\r\n");
      out.write("\t\t\t\t\t<td width=350>\r\n");
      out.write("\t\t\t\t\t\t");

							if (sRoom != null) {
							if (room == 1) {
						
      out.write(" VIP<input type=hidden name=\"room\" value=1> ");

 	} else if (room == 2) {
 
      out.write(" Normal<input type=hidden name=\"room\" value=2> ");

 	} else if (room == 3) {
 
      out.write(" Reasonable<input type=hidden name=\"room\" value=3> ");

 	}

 } else {
 
      out.write(" <select name=room id=room>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=1>VIP\r\n");
      out.write("\t\t\t\t\t\t\t<option value=2>Normal\r\n");
      out.write("\t\t\t\t\t\t\t<option value=3>Reasonable\r\n");
      out.write("\t\t\t\t\t</select> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Address</td>\r\n");
      out.write("\t\t\t\t\t<td width=350><input type=\"text\" name=\"addr\" id=\"addr\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 350px; font-family: 'Noto Serif KR', serif; width:90px;\"><span class=\"error\" id=\"errMsg_04\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 1em\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Tel</td>\r\n");
      out.write("\t\t\t\t\t<td width=350><input type=\"search\" name=\"tel\" id=\"tel\" style=\"font-family: 'Noto Serif KR', serif; width:90px;\">ex)\r\n");
      out.write("\t\t\t\t\t\t010-0000-0000 <span class=\"error\" id=\"errMsg_03\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 1em; font-family: 'Noto Serif KR', serif;\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Depositor</td>\r\n");
      out.write("\t\t\t\t\t<td width=350><input type=\"text\" name=\"inname\" id=\"inname\" style=\"font-family: 'Noto Serif KR', serif; width:90px;\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\" id=\"errMsg_02\" style=\"font-size: 1em; font-family: 'Noto Serif KR', serif;\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100 align=center>Comment</td>\r\n");
      out.write("\t\t\t\t\t<td width=350><input type=\"text\" name=\"comment\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 350px; font-family: 'Noto Serif KR', serif; width:90px;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=2 align=center><button type=submit class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tid=submit>Submit</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<!-- JS here -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t\t<script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <!-- Jquery Mobile Menu -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("        <!-- Date Picker -->\r\n");
      out.write("        <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("\t\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- contact js -->\r\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
