/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-20 06:39:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.net.URLDecoder;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title>Hotel</title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CSS here -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar orientationEvent;\r\n");
      out.write("\tvar uAgent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\tvar mobilePhones = 'android';\r\n");
      out.write("\tif (uAgent.indexOf(mobilePhones) != -1) {\r\n");
      out.write("\t\torientationEvent = \"resize\"; // 안드로이드는 resize로 들어옴\t\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\torientationEvent = \"orientationchange\"; // 아이폰은 이렇게 들어옴\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.addEventListener(orientationEvent, function() {\r\n");
      out.write("\t\t// alert(\"회전했어요\");\r\n");
      out.write("\t\tlocation.href('#');\r\n");
      out.write("\t}, false);\r\n");
      out.write("\r\n");
      out.write("\tvar prevScreen = 0;\r\n");
      out.write("\tvar sv_prevScreen = 0;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction prevShow() {\r\n");
      out.write("\t\tScreenShow(prevScreen);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar muCnt = 5; // 서브메뉴\r\n");
      out.write("\tvar scCnt = 15; // 화면\r\n");
      out.write("\r\n");
      out.write("\tfunction fncShow(pos) {\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\tfor (i = 0; i < scCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"s\" + i);\r\n");
      out.write("\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (i = 0; i < muCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"menu\" + i);\r\n");
      out.write("\t\t\tvar obj2 = document.getElementById(\"m\" + i);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (i == pos) {\r\n");
      out.write("\t\t\t\tobj.style.display = '';\r\n");
      out.write("\t\t\t\tobj2.style.background = \"#fff5f5\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t\t\tobj2.style.background = \"#ffffff\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar scCnt = 15;\r\n");
      out.write("\tvar ScrObj;\r\n");
      out.write("\r\n");
      out.write("\tvar timer1;\r\n");
      out.write("\r\n");
      out.write("\tfunction ScrAnimation() {\r\n");
      out.write("\t\tvar offset = -50;\r\n");
      out.write("\r\n");
      out.write("\t\tif (parseInt(ScrObj.style.left) > 10) {\r\n");
      out.write("\t\t\tScrObj.style.left = parseInt(ScrObj.style.left) + offset + \"px\";\r\n");
      out.write("\t\t\ttimer1 = setTimeout(\"ScrAnimation()\", 1);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tScrObj.style.left = 5;\r\n");
      out.write("\t\t\tclearTimeout(timer1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ScreenShow(pos) {\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\t// 모든 메뉴 페이지는 막는다.\r\n");
      out.write("\t\tfor (i = 0; i < muCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"menu\" + i);\r\n");
      out.write("\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < scCnt; i++) {\r\n");
      out.write("\t\t\tvar obj = document.getElementById(\"s\" + i);\r\n");
      out.write("\t\t\tif (i == pos) {\r\n");
      out.write("\t\t\t\tprevScreen = sv_prevScreen;\r\n");
      out.write("\t\t\t\tsv_prevScreen = i;\r\n");
      out.write("\t\t\t\tobj.style.display = '';\r\n");
      out.write("\t\t\t\t//obj.style.position = \"relative\";\r\n");
      out.write("\t\t\t\tobj.style.top = 35;\r\n");
      out.write("\t\t\t\tobj.style.left = screen.width;\r\n");
      out.write("\t\t\t\tobj.style.height = screen.height - 120;\r\n");
      out.write("\t\t\t\tScrObj = obj;\r\n");
      out.write("\t\t\t\tScrAnimation();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tobj.style.display = 'none';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("li {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmargin: 2;\r\n");
      out.write("\tpadding: 10;\r\n");
      out.write("\theight: 20;\r\n");
      out.write("\tbackground-color: #aaaa00;\r\n");
      out.write("\tborder: 2px;\r\n");
      out.write("\tsolid: red;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmargin: 2;\r\n");
      out.write("\tpadding: 10;\r\n");
      out.write("\theight: 20;\r\n");
      out.write("\tbackground-color: #bbaabb;\r\n");
      out.write("\tborder: 2px;\r\n");
      out.write("\tsolid: red;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>Welcome to Real Light Resort.</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body BACKGROUND=\"./image/bg.png\" onload='ScreenShow(0);' style=\"font-family: 'Cinzel', serif;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <strong>Real Light</b>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

	Calendar cal = Calendar.getInstance();
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 hh시 mm분 ss초");
	String myTime = URLEncoder.encode(sdf.format(cal.getTime()), "UTF-8"); //쿠키에 저장할 값
	String myTime2 = sdf.format(cal.getTime()); //쿠키에 저장할 값
	
	Cookie[] cookies = request.getCookies(); // 쿠키들 모두 얻기, 배열값으로
if (cookies != null) {
	
for (int i = 0; i < cookies.length; i++) { // 배열길이만큼 for문 돌림
	Cookie thisCookie = cookies[i]; // 배열1개의 이름
	if ("time".equals(thisCookie.getName())) { // thisCookie가 name이라는 id이면
		out.println("최근 방문일은 ("+URLDecoder.decode(thisCookie.getValue(), "UTF-8")+") 입니다.<br>"); // 그 id의 값을 출력
	}
}
} else {
	out.println("최근 방문일은 ("+myTime2+") 입니다.<br>");
}

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

 cookies = request.getCookies(); // 쿠키들 얻기
	if (cookies != null) {
		
for (int i = 0; i < cookies.length; i++) { // 배열길이만큼 for문 돌림
	Cookie thisCookie = cookies[i]; // 쿠키 1개 이름 설정
	if ("time".equals(thisCookie.getName())) { // id가 name인 쿠키가 있으면
		thisCookie.setMaxAge(0); // 유효기간 0으로 설정 -> 지워짐
		response.addCookie(thisCookie); // 쿠키를 세팅
	}
}
	}

      out.write('\r');
      out.write('\n');
      out.write('	');

Cookie cookieName = new Cookie("time", myTime); // "name"이라는 id로 myName값 저장
cookieName.setMaxAge(-1); // 브라우저 켜있을 때까지 저장
response.addCookie(cookieName); // response 객체에 보내야 사용가능

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div id=\"container\"\r\n");
      out.write("\t\t\tstyle=\"width: device-width; height: device-height;\">\r\n");
      out.write("\t\t\t<div id=\"header1\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #ffffff; height: 60px; width: 15%; float: left;\"\r\n");
      out.write("\t\t\t\tonclick='prevShow();'>\r\n");
      out.write("\t\t\t\t<center><img src=\"https://img.icons8.com/material/96/000000/back--v1.png\" width=50px height=50px></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"header2\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #ffffff; height: 60px; width: 70%; float: left;\" onclick='ScreenShow(0);'>\r\n");
      out.write("\t\t\t\t<center style=\"margin: 10px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./image/reallightresort.png\"\r\n");
      out.write("\t\t\t\t\twidth=\"100\" height=\"40\" border=\"0\">\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"header3\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #ffffff; height: 60px; width: 15%; float: left;\"\r\n");
      out.write("\t\t\t\tonclick='ScreenShow(0);'>\r\n");
      out.write("\t\t\t\t<center><img src=\"https://img.icons8.com/material-outlined/96/000000/home-page.png\" width=40px height=40px></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"menu0\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #eeeeee; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<b>About</b>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(0);'><b>Real Light</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(1);'><b>VIP Room</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(2);'><b>Normal Room</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(3);'><b>Reasonable Room</b></li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu1\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #eeeeee; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<b>Contact</b>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(4);'><b>Location</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(5);'><b>By Public transport</li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(6);'><b>By Car</li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu2\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #eeeeee; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<b>Travel</b>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(7);'><b style=\"font-family: 'Noto Serif KR', serif;\">높아산</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(8);'><b style=\"font-family: 'Noto Serif KR', serif;\">조아해수욕장</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(9);'><b style=\"font-family: 'Noto Serif KR', serif;\">따끈온천</b></li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu3\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #eeeeee; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<b>Booking</b>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(10);'><b>Reservation Status</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(11);'><b>Reservation</b></li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu4\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #eeeeee; display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<b>Notice</b>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(12);'><b>Notice</b></li>\r\n");
      out.write("\t\t\t\t<li onclick='ScreenShow(13);'><b>Review</b></li> <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"s0\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t        <!-- slider Area Start-->\r\n");
      out.write("        <div class=\"slider-area \">\r\n");
      out.write("            <!-- Mobile Menu -->\r\n");
      out.write("            <div class=\"slider-active dot-style\">\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"assets/img/hero/h1_hero.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"./image/3.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"assets/img/hero/h1_hero.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slider Area End-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s1\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"a_01.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s2\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"a_02.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s3\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none; width: device-width;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"a_03.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s4\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"b_01.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s5\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"b_02.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s6\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"b_03.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s7\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"c_01.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s8\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"c_02.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s9\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"c_03.html\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s10\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"d_01_m.jsp\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s11\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t<iframe src=\"d_02_m.jsp\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s12\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe src=\"gongji_list.jsp\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t<div id=\"s13\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe src=\"gongji_list2.jsp\" frameborder=\"0\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tbordercolor=\"white\" width=320px height=420px marginwidth=\"0\"\r\n");
      out.write("\t\t\t\t\tmarginheight=\"0\" scrolling=\"yes\"></iframe></div>\r\n");
      out.write("\t\t\t<div id=\"s14\"\r\n");
      out.write("\t\t\t\tstyle=\"background-image: url(./image/bg.png); display: none;\">\r\n");
      out.write("\t\t\t\t나 메뉴 4_3에 대한 화면</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"m0\" onclick='fncShow(0);'\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 1%; background-color: #ffffff; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<img src=\"https://img.icons8.com/dusk/64/000000/3-star-hotel.png\" width=40px height=40px><br>\r\n");
      out.write("\t\t\t\t\t<font size=2>About</font>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"m1\" onclick='fncShow(1);'\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 21%; background-color: #ffffff; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<img src=\"https://img.icons8.com/dusk/96/000000/worldwide-location.png\" width=40px height=40px><br>\r\n");
      out.write("\t\t\t\t\t<font size=2>Contact</font>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"m2\" onclick='fncShow(2);'\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 41%; background-color: #ffffff; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<img src=\"https://img.icons8.com/dusk/64/000000/passenger-with-baggage.png\" width=40px height=40px><br>\r\n");
      out.write("\t\t\t\t\t<font size=2>Travel</font>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"m3\" onclick='fncShow(3);'\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 61%; background-color: #ffffff; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<img src=\"https://img.icons8.com/dusk/64/000000/hotel-information.png\" width=40px height=40px><br>\r\n");
      out.write("\t\t\t\t\t<font size=2>Booking</font>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"m4\" onclick='fncShow(4);'\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; bottom: 3px; position: absolute; left: 81%; background-color: #ffffff; height: 60px; width: 18%; float: left;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<img src=\"https://img.icons8.com/dusk/64/000000/survey.png\" width=40px height=40px><br>\r\n");
      out.write("\t\t\t\t\t<font size=2>Notice</font>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS here -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t\t<script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <!-- Jquery Mobile Menu -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("        <!-- Date Picker -->\r\n");
      out.write("        <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("\t\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- contact js -->\r\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
