/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-20 05:30:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.net.URLDecoder;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title>Hotel</title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CSS here -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/gijgo.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slicknav.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/animate.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/fontawesome-all.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("<title>Welcome to Real Light Resort.</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body BACKGROUND=\"./image/bg.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader Start -->\r\n");
      out.write("    <div id=\"preloader-active\">\r\n");
      out.write("        <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"preloader-inner position-relative\">\r\n");
      out.write("                <div class=\"preloader-circle\"></div>\r\n");
      out.write("                <div class=\"preloader-img pere-text\">\r\n");
      out.write("                    <strong>Real Light</b>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- slider Area Start-->\r\n");
      out.write("        <div class=\"slider-area \">\r\n");
      out.write("            <!-- Mobile Menu -->\r\n");
      out.write("            <div class=\"slider-active dot-style\">\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"assets/img/hero/h1_hero.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"./image/3.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slider  hero-overly slider-height d-flex align-items-center\" data-background=\"assets/img/hero/h1_hero.jpg\" >\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("                            <div class=\"col-xl-9\">\r\n");
      out.write("                                <div class=\"h1-slider-caption\">\r\n");
      out.write("                                    <h1 data-animation=\"fadeInUp\" data-delay=\".4s\">Real Light in the city</h1>\r\n");
      out.write("                                    <h3 data-animation=\"fadeInDown\" data-delay=\".4s\">Hotel & Resort</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slider Area End-->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

	Calendar cal = Calendar.getInstance();
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 hh시 mm분 ss초");
	String myTime = URLEncoder.encode(sdf.format(cal.getTime()), "UTF-8"); //쿠키에 저장할 값
	String myTime2 = sdf.format(cal.getTime()); //쿠키에 저장할 값
	
	Cookie[] cookies = request.getCookies(); // 쿠키들 모두 얻기, 배열값으로
if (cookies != null) {
	
for (int i = 0; i < cookies.length; i++) { // 배열길이만큼 for문 돌림
	Cookie thisCookie = cookies[i]; // 배열1개의 이름
	if ("time".equals(thisCookie.getName())) { // thisCookie가 name이라는 id이면
		out.println("최근 방문일은 ("+URLDecoder.decode(thisCookie.getValue(), "UTF-8")+") 입니다.<br>"); // 그 id의 값을 출력
	}
}
} else {
	out.println("최근 방문일은 ("+myTime2+") 입니다.<br>");
}

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

 cookies = request.getCookies(); // 쿠키들 얻기
	if (cookies != null) {
		
for (int i = 0; i < cookies.length; i++) { // 배열길이만큼 for문 돌림
	Cookie thisCookie = cookies[i]; // 쿠키 1개 이름 설정
	if ("time".equals(thisCookie.getName())) { // id가 name인 쿠키가 있으면
		thisCookie.setMaxAge(0); // 유효기간 0으로 설정 -> 지워짐
		response.addCookie(thisCookie); // 쿠키를 세팅
	}
}
	}

      out.write('\r');
      out.write('\n');
      out.write('	');

Cookie cookieName = new Cookie("time", myTime); // "name"이라는 id로 myName값 저장
cookieName.setMaxAge(-1); // 브라우저 켜있을 때까지 저장
response.addCookie(cookieName); // response 객체에 보내야 사용가능

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Make customer Start-->\r\n");
      out.write("        <section class=\"make-customer-area customar-padding fix\">\r\n");
      out.write("            <div class=\"container-fluid p-0\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                   <div class=\"col-xl-5 col-lg-6\">\r\n");
      out.write("                        <div class=\"customer-img mb-120\">\r\n");
      out.write("                            <img src=\"assets/img/customer/customar1.png\" class=\"customar-img1\" alt=\"\">\r\n");
      out.write("                            <img src=\"assets/img/customer/customar2.png\" class=\"customar-img2\" alt=\"\">\r\n");
      out.write("                            <div class=\"service-experience heartbeat\">\r\n");
      out.write("                                <h3>25 Years of Service<br>Experience</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                    <div class=\" col-xl-4 col-lg-4\">\r\n");
      out.write("                        <div class=\"customer-caption\">\r\n");
      out.write("                            <span>About our company</span>\r\n");
      out.write("                            <h2>Make the customer the hero of your story</h2>\r\n");
      out.write("                            <div class=\"caption-details\">\r\n");
      out.write("                                <p class=\"pera-dtails\">As a representative luxury resort in Korea, the concept of \"a place where daily life becomes the best moment\" has been newly introduced, and it has been reborn as a space where customers' high-quality lifestyles such as high-end food culture, art, beauty, shopping, wedding, and entertainment are suggested. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Make customer End-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Room Start -->\r\n");
      out.write("        <section class=\"room-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-8\">\r\n");
      out.write("                        <!--font-back-tittle  -->\r\n");
      out.write("                        <div class=\"font-back-tittle mb-45\">\r\n");
      out.write("                            <div class=\"archivment-front\">\r\n");
      out.write("                                <h3>Our Rooms</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3 class=\"archivment-back\">Our Rooms</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-6 col-md-6\">\r\n");
      out.write("                        <!-- Single Room -->\r\n");
      out.write("                        <div class=\"single-room mb-50\">\r\n");
      out.write("                            <div class=\"room-img\">\r\n");
      out.write("                               <a href=\"a_01.html\"><img src=\"assets/img/rooms/room1.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"room-caption\">\r\n");
      out.write("                                <h3><a href=\"rooms.html\">VIP Room</a></h3>\r\n");
      out.write("                                <div class=\"per-night\">\r\n");
      out.write("                                    <span><u>￦</u>150,000 <span>/ par night</span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-6 col-md-6\">\r\n");
      out.write("                        <!-- Single Room -->\r\n");
      out.write("                        <div class=\"single-room mb-50\">\r\n");
      out.write("                            <div class=\"room-img\">\r\n");
      out.write("                               <a href=\"a_02.html\"><img src=\"assets/img/rooms/room2.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"room-caption\">\r\n");
      out.write("                                <h3><a href=\"rooms.html\">Normal Room</a></h3>\r\n");
      out.write("                                <div class=\"per-night\">\r\n");
      out.write("                                    <span><u>￦</u>80,000 <span>/ par night</span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-6 col-md-6\">\r\n");
      out.write("                        <!-- Single Room -->\r\n");
      out.write("                        <div class=\"single-room mb-50\">\r\n");
      out.write("                            <div class=\"room-img\">\r\n");
      out.write("                               <a href=\"a_03.html\"> <img src=\"assets/img/rooms/room3.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"room-caption\">\r\n");
      out.write("                                <h3><a href=\"rooms.html\">Reasonable Room</a></h3>\r\n");
      out.write("                                <div class=\"per-night\">\r\n");
      out.write("                                    <span><u>￦</u>100,000 <span>/ par night</span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"room-btn pt-70\">\r\n");
      out.write("                        <a href=\"a_01.html\" class=\"btn view-btn1\">View more  <i class=\"ti-angle-right\"></i> </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Room End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Dining Start -->\r\n");
      out.write("        <div class=\"dining-area dining-padding-top\">\r\n");
      out.write("            <!-- Single Left img -->\r\n");
      out.write("            <div class=\"single-dining-area left-img\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row justify-content-end\">\r\n");
      out.write("                        <div class=\"col-lg-8 col-md-8\">\r\n");
      out.write("                            <div class=\"dining-caption\">\r\n");
      out.write("                                <span>Our restaurant</span>\r\n");
      out.write("                                <h3>Dining & Drinks</h3>\r\n");
      out.write("                                <p>Elegant interior decoration, soft lighting, and professional and attentive staff services also add to the special encounter with a valued person.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("            <!-- single Right img -->\r\n");
      out.write("            <div class=\"single-dining-area right-img\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row justify-content-start\">\r\n");
      out.write("                        <div class=\"col-lg-8 col-md-8\">\r\n");
      out.write("                            <div class=\"dining-caption text-right\">\r\n");
      out.write("                                <span>Our Pool</span>\r\n");
      out.write("                                <h3>Swimming Pool</h3>\r\n");
      out.write("                                <p>The first hot water pool, rooftop, cabana, and other outdoor lifestyle in Bundang Special Resort.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Dining End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Testimonial Start -->\r\n");
      out.write("        <div class=\"testimonial-area testimonial-padding\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-9 col-lg-9 col-md-9\">\r\n");
      out.write("                        <div class=\"h1-testimonial-active\">\r\n");
      out.write("                            <!-- Single Testimonial -->\r\n");
      out.write("                            <div class=\"single-testimonial pt-65\">\r\n");
      out.write("                                <!-- Testimonial tittle -->\r\n");
      out.write("                                <div class=\"font-back-tittle mb-105\">\r\n");
      out.write("                                    <div class=\"archivment-front\">\r\n");
      out.write("                                        <img src=\"assets/img/logo/testimonial.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h3 class=\"archivment-back\">Testimonial</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                 <!-- Testimonial Content -->\r\n");
      out.write("                                <div class=\"testimonial-caption text-center\">\r\n");
      out.write("                                    <p>Yorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <!-- Rattion -->\r\n");
      out.write("                                    <div class=\"testimonial-ratting\">\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"rattiong-caption\">\r\n");
      out.write("                                        <span>Clifford Frazier, <span>Regular Client</span> </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Single Testimonial -->\r\n");
      out.write("                            <div class=\"single-testimonial  pt-65\">\r\n");
      out.write("                                <!-- Testimonial tittle -->\r\n");
      out.write("                                <div class=\"font-back-tittle mb-105\">\r\n");
      out.write("                                    <div class=\"archivment-front\">\r\n");
      out.write("                                        <img src=\"assets/img/logo/testimonial.png\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h3 class=\"archivment-back\">Testimonial</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Testimonial Content -->\r\n");
      out.write("                                <div class=\"testimonial-caption text-center\">\r\n");
      out.write("                                    <p>Yorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"testimonial-ratting\">\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fas fa-star\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fas fa-star\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fas fa-star\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fas fa-star\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fas fa-star\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"rattiong-caption\">\r\n");
      out.write("                                        <span>Clifford Frazier, <span>Regular Client</span> </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Gallery img Start-->\r\n");
      out.write("        <div class=\"gallery-area fix\">\r\n");
      out.write("            <div class=\"container-fluid p-0\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"gallery-active owl-carousel\">\r\n");
      out.write("                            <div class=\"gallery-img\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"assets/img/gallery/gallery1.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gallery-img\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"assets/img/gallery/gallery2.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gallery-img\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"assets/img/gallery/gallery3.jpg\" alt=\"\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Gallery img End-->\r\n");
      out.write("    </main>\r\n");
      out.write("   <footer>\r\n");
      out.write("       <!-- Footer Start-->\r\n");
      out.write("       <div class=\"footer-area black-bg footer-padding\">\r\n");
      out.write("           <div class=\"container\">\r\n");
      out.write("               <div class=\"row d-flex justify-content-between\">\r\n");
      out.write("                   <div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                      <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                         <!-- logo -->\r\n");
      out.write("                         <div class=\"footer-logo\">\r\n");
      out.write("                           <a href=\"main.jsp\"><img src=\"assets/img/logo/reallightresort2.png\" width=200 height=80 alt=\"\"></a>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <div class=\"footer-social footer-social2\">\r\n");
      out.write("                             <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                             <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                             <a href=\"#\"><i class=\"fas fa-globe\"></i></a>\r\n");
      out.write("                             <a href=\"#\"><i class=\"fab fa-behance\"></i></a>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <div class=\"footer-pera\">\r\n");
      out.write("                              <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ti-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"col-xl-3 col-lg-3 col-md-3 col-sm-5\">\r\n");
      out.write("                       <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                           <div class=\"footer-tittle\">\r\n");
      out.write("                               <h4>Quick Links</h4>\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                   <li><a href=\"#\">About Mariana</a></li>\r\n");
      out.write("                                   <li><a href=\"#\">Our Best Rooms</a></li>\r\n");
      out.write("                                   <li><a href=\"#\">Our Photo Gallary</a></li>\r\n");
      out.write("                                   <li><a href=\"#\">Pool Service</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"col-xl-3 col-lg-3 col-md-3 col-sm-3\">\r\n");
      out.write("                       <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                           <div class=\"footer-tittle\">\r\n");
      out.write("                               <h4>Reservations</h4>\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                   <li><a href=\"#\">Tel: 010 1234 1324</a></li>\r\n");
      out.write("                                   <li><a href=\"#\">Skype: Reallightbooking</a></li>\r\n");
      out.write("                                   <li><a href=\"#\">reservations@reallight.com</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"col-xl-3 col-lg-3 col-md-4  col-sm-5\">\r\n");
      out.write("                       <div class=\"single-footer-caption mb-30\">\r\n");
      out.write("                           <div class=\"footer-tittle\">\r\n");
      out.write("                               <h4>Our Location</h4>\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                   <li><a href=\"#\">경기도 성남시 분당구 </a></li>\r\n");
      out.write("                                   <li><a href=\"#\">황새울로 329번길 5</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                               <!-- Form -->\r\n");
      out.write("                                <div class=\"footer-form\" >\r\n");
      out.write("                                    <div id=\"mc_embed_signup\">\r\n");
      out.write("                                        <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("                                        method=\"get\" class=\"subscribe_form relative mail_part\">\r\n");
      out.write("                                            <input type=\"email\" name=\"email\" id=\"newsletter-form-email\" placeholder=\"Email Address\"\r\n");
      out.write("                                            class=\"placeholder hide-on-focus\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("                                            onblur=\"this.placeholder = ' Email Address '\">\r\n");
      out.write("                                            <div class=\"form-icon\">\r\n");
      out.write("                                              <button type=\"submit\" name=\"submit\" id=\"newsletter-submit\"\r\n");
      out.write("                                              class=\"email_icon newsletter-submit button-contactForm\"><img src=\"assets/img/logo/form-iocn.jpg\" alt=\"\"></button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"mt-10 info\"></div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- Footer End-->\r\n");
      out.write("   </footer>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- JS here -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("        <script src=\"./assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t\t<script src=\"./assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <!-- Jquery Mobile Menu -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("        <script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/slick.min.js\"></script>\r\n");
      out.write("        <!-- Date Picker -->\r\n");
      out.write("        <script src=\"./assets/js/gijgo.min.js\"></script>\r\n");
      out.write("\t\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("        <script src=\"./assets/js/wow.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/animated.headline.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("        <script src=\"./assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- contact js -->\r\n");
      out.write("        <script src=\"./assets/js/contact.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("        <script src=\"./assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
